version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
<<<<<<< HEAD
      - warehouse-prod
=======
      - warehouse-stage
>>>>>>> dev

  app:
    build: .
    ports:
<<<<<<< HEAD
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    networks:
      - warehouse-prod
=======
      - "127.0.0.1:5001:5000"
    depends_on:
      - redis
    networks:
      - warehouse-stage
>>>>>>> dev
    volumes:
      - ./data:/app/data  

networks:
<<<<<<< HEAD
  warehouse-prod:
=======
  warehouse-stage:
>>>>>>> dev
    driver: bridge
