version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - warehouse-stage

  app:
    build: .
    ports:
      - "127.0.0.1:5001:5000"
    depends_on:
      - redis
    networks:
      - warehouse-stage
    volumes:
      - ./data:/app/data  

networks:
  warehouse-stage:
    driver: bridge
