version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - warehouse-prod

  app:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    networks:
      - warehouse-prod
    volumes:
      - ./data:/app/data  

networks:
  warehouse-prod:
    driver: bridge
